PSI-X/Models/Company.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PSI_X.Models
{
    public class Company
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string TypeOfCompany { get; set; }
    }
}

PSI-X/ViewModels/CompanyViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PSI_X.ViewModels
{
    public class CompanyViewModel
    {
        [Required]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Too short name")]
        public string Name { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Too short name")]
        public string Address { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Too short name")]
        public string TypeOfCompany { get; set; }
    }
}

PSI-X/Controllers/CompaniesController.cs
using PSI_X.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PSI_X.ViewModels;
using System.Collections;

namespace PSI_X.Controllers
{
   //[Authorize]
    public class CompaniesController : Controller
    {
        private DbContentPSI db = new DbContentPSI();
        // GET: Companies
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Post()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Post(CompanyViewModel company)
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login");
            }
            else
            {
                /*without validations yet */
                ViewBag.RespondMsg = "";
                Company newCompany = new Company();
                if (ModelState.IsValid)
                {
                    newCompany.Address = company.Address;
                    newCompany.TypeOfCompany = company.TypeOfCompany;
                    newCompany.Name = company.Name;
                    db.Companies.Add(newCompany);
                    db.SaveChanges();
                    ViewBag.RespondMsg = "Succeeded";
                    ModelState.Clear();
                }
                return View();
            }
        }
        public ActionResult Show()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login");
            }
            else
            {
                IEnumerable<Company> comp = db.Companies.ToList();
                return View(comp);
            }
            
        }
    }
}

PSI-X/Views/Companies/Post.cshtml
@model PSI_X.ViewModels.CompanyViewModel
@{
    ViewBag.Title = "Post";
}



<div class="container">
    <h3 style="padding-top: 50px">Insert new Company</h3>
    <hr />
    <div class="col-md-4 col-md-offset-4">
        @using (Html.BeginForm("Post", "Companies", FormMethod.Post))
        {
            @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @placeholder = "Name" })
            <br />
            @Html.TextBoxFor(model => model.Address, new { @class = "form-control", @placeholder = "Address" })
            <br />
            @Html.TextBoxFor(model => model.TypeOfCompany, new { @class = "form-control", @placeholder = "Type of Company" })
            <br />
            <input type="submit" value="Submit" class="btn btn-success" />
        }
    </div>
</div>
@if(ViewBag.RespondMsg == "Succeeded")
{
    <p style="color:forestgreen">Succeeded</p>
}

PSI-X/Views/Companies/Show.cshtml
@model  IEnumerable<PSI_X.Models.Company>
    @{
        ViewBag.Title = "Show";
    }
    <br />
    <br />
    <br />
    <table class="table table-condensed">
        <thead>
            <tr>
                <th>Name</th>
                <th>Address</th>
                <th>Type of Company</th>
            </tr>
        </thead>
        <tbody>
        @foreach (var name in Model)
        {
            <tr>
                <td>@name.Name</td>
                <td>@name.Address</td>
                <td>@name.TypeOfCompany</td>
            </tr>
        }
        </tbody>
    </table>
   