PSI-X/Models/CompanyCode.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PSI_X.Models
{
    public class CompanyCode
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string Name { get; set; } /*for what kind of product the code is created, coffee, tea... */
        public int Code { get; set; }
        public int Points { get; set; }
        public int TimesUsed { get; set; }
    }
}

PSI-X/ViewModels/CompanyCodeViewModel.cs
using PSI_X.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PSI_X.ViewModels
{
    public class CompanyCodeViewModel
    {
        public CompanyCode codesForCompany { get; set; }
        public IEnumerable<Company> companiesCodeView { get; set; }
    }
}

PSI-X/Controllers/CompanyCodesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PSI_X.Models;
using PSI_X.ViewModels;

namespace PSI_X.Controllers
{
    //[Authorize]
    public class CompanyCodesController : Controller
    {
        // GET: CompanyCodes
        private DbContentPSI db = new DbContentPSI();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PostCode()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login");
            }
            else
            {
                var types = db.Companies.ToList();
                var codesList = new CompanyCodeViewModel
                {
                    codesForCompany = new CompanyCode(),
                    companiesCodeView = types
                };

                return View("SaveRecord", codesList);
            }
        }

        [HttpPost]
        public ActionResult SaveRecord(CompanyCodeViewModel code)
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login");
            }
            else
            {
                bool codeExists = false;
                DbContentPSI db = new DbContentPSI();
                var codes = db.Codes;

                foreach (var c in codes)
                {
                    if (c.Code == code.codesForCompany.Code)
                    {
                        codeExists = true;
                        break;
                    }
                }

                if (!codeExists)
                {
                    CompanyCode userCode = new CompanyCode();

                    userCode.Code = code.codesForCompany.Code;
                    userCode.CompanyId = code.codesForCompany.CompanyId;
                    userCode.Name = code.codesForCompany.Name;
                    userCode.Points = code.codesForCompany.Points;
                    db.Codes.Add(userCode);
                    db.SaveChanges();
                    ViewBag.Msg = "Succeded";
                    ViewBag.ResultMessage = "Code was successfully added.";
                    return View("Result");
                }
                else
                {
                    ViewBag.Msg = "Exact code already exists.";
                    ViewBag.ResultMessage = "Exact code already exists. Please try again.";
                    return View("Result");
                }
            }
        }
        public ActionResult Show()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login");
            }
            else
            {
                ListOfCompanyCodes vm = new ListOfCompanyCodes()
                {
                    codesForCompany = db.Codes.ToList(),
                    companiesCodeView = db.Companies.ToList()
                };

                return View(vm);
            }
        }

        public ActionResult Result(string message)
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login");
            }
            else
            {
                return View();
            }
        }

        public ActionResult CodesUsage()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login");
            }
            else
            {
                var companies = db.Companies;
                var companyCodes = db.Codes;
                List<UsageViewModel> model = new List<UsageViewModel>();

                foreach (var company in companies)
                {
                    foreach (var code in companyCodes)
                    {
                        if (company.Id == code.CompanyId)
                        {
                            var item = new UsageViewModel();
                            item.CompaniesList = db.Companies.ToList();
                            item.CodeName = code.Name;
                            item.CompanyName = company.Name;
                            item.TimesUsed = code.TimesUsed;
                            model.Add(item);
                        }
                    }
                }

                return View(model);
            }
        }
    }
}

PSI-X/Views/CompanyCodes/CodesUsage.cshtml
<br />
<br />
<br />
@foreach (var company in Model[0].CompaniesList)
{
    <h3>@company.Name</h3>
    <table class="table table-condensed">
        <tr>
            <th>Code name</th>
            <th>Times used</th>
        </tr>
        @foreach (var code in Model)
        {
            if (code.CompanyName.ToString().StartsWith(company.Name.ToString()))
            {
                <tr>
                    <td>@code.CodeName</td>
                    <td>@code.TimesUsed.ToString()</td>
                </tr>
            }
        }
    </table>
}

PSI-X/Views/CompanyCodes/Result.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<br />
<h2>@ViewBag.ResultMessage</h2>

PSI-X/Views/CompanyCodes/SaveRecord.cshtml
@model PSI_X.ViewModels.CompanyCodeViewModel
@{
    ViewBag.Title = "PostCode";
}


<div class="container">
    <h3 style="padding-top: 50px" >Insert new Code</h3>
    <hr />
    <div class="col-md-4 col-md-offset-4">
        @using (Html.BeginForm("SaveRecord", "CompanyCodes", FormMethod.Post))
        {
            <label>Name</label>
            @Html.TextBoxFor(model => model.codesForCompany.Name, new { @class = "form-control", @placeholder = "Name" })
            <br />
            <label>Code</label>
            @Html.TextBoxFor(model => model.codesForCompany.Code, new { @class = "form-control", @placeholder = "Code" })
            <br />
            <div class="form-group">
                
                @try
                {
                    <label>Company</label>
                    @Html.DropDownListFor(m => m.codesForCompany.CompanyId, new SelectList(Model.companiesCodeView, "Id", "Name"), "", new { @class = "form-control" })
                }
                catch (NullReferenceException e)
                {

                }
               
            </div>
            <label>Points</label>
            @Html.TextBoxFor(model => model.codesForCompany.Points, new { @class = "form-control", @placeholder = "Points" })
            <br />
            <input type="submit" value="Submit" class="btn btn-success" />
        }
    </div>
</div>
@if(ViewBag.Msg == "Succeded")
{
    <p align="center">New code was successfully created!</p>
}
@if(ViewBag.Msg == "Exact code already exists.")
{
    <p align="center">Exact code already exists. Please specify other code.</p>
}

PSI-X/Views/CompanyCodes/Show.cshtml
@model  PSI_X.ViewModels.ListOfCompanyCodes
@{
    ViewBag.Title = "Show All codes of...";
}

<h2>Show</h2>
@foreach (var kompanija in Model.companiesCodeView)
{
    <h3>@kompanija.Name</h3>
    <table class="table table-condensed">
        <thead>
            <tr>
                <th>Code</th>
                <th>Name</th>
                <th>Points</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var kodas in Model.codesForCompany)
            {
                <tr>
                    @if (kompanija.Id == kodas.CompanyId)
                    {
                        <td>@kodas.Code </td>
                        <td>@kodas.Name</td>
                        <td>@kodas.Points</td>
                    }
                </tr>
            }
          
        </tbody>
    </table>
  }