PSI-X/Models/Rewards.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PSI_X.Models
{
    public class Rewards
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string RewardName { get; set; }
        public int RequiredPoints { get; set; }
    }
}

PSI-X/ViewModels/RewardsViewModel.cs
namespace PSI_X.ViewModels
{
    public class RewardsViewModel
    {
        public string CompanyName { get; set; }
        public string RewardName { get; set; }
        public int RequiredPoints { get; set; }
    }
}

PSI-X/Controllers/RewardsController.cs
using PSI_X.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PSI_X.Models;

namespace PSI_X.Controllers
{
    public class RewardsController : Controller
    {
        DbContentPSI database = new DbContentPSI();
        // GET: Rewards
        public ActionResult AllRewards()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login");
            }
            else
            {
                var companies = database.Companies;
                var rewards = database.Rewards;
                List<RewardsViewModel> model = new List<RewardsViewModel>();

                foreach (var company in companies)
                {
                    foreach (var reward in rewards)
                    {
                        if (company.Id == reward.CompanyId)
                        {
                            var item = new RewardsViewModel();
                            item.CompanyName = company.Name;
                            item.RewardName = reward.RewardName;
                            item.RequiredPoints = reward.RequiredPoints;
                            model.Add(item);
                        }
                    }
                }

                return View(model);
            }
        }

        public ActionResult NewReward()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login");
            }
            else
            {
                var model = new RewardAddViewModel();
                model.companies = database.Companies;
                model.reward = new Rewards();

                return View("SaveReward", model);
            }
        }

        [HttpPost]
        public ActionResult SaveReward(RewardAddViewModel model)
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login");
            }
            else
            {
                database.Rewards.Add(model.reward);
                database.SaveChanges();

                ViewBag.Message = "New reward was successfully added.";
                return View("Result");
            }
        }

        public ActionResult Index()
        {
            int usrId = int.Parse(Session["Id"].ToString());
            IEnumerable<UserPoints> userPointsList = database.UserPoints.ToList();
            IEnumerable<Rewards> rewards = database.Rewards.ToList();
            List<Company> companies = database.Companies.ToList();
            List<UserRewardsViewModel> rewardsList = new List<UserRewardsViewModel>();
            foreach (var record in userPointsList)
            {
                if(record.UserId == usrId)
                {
                    foreach (var reward in rewards)
                    {
                        if (record.UserCompanyPoints >= reward.RequiredPoints 
                            && record.CompanyId == reward.CompanyId)
                        {
                            foreach (var company in companies)
                            {
                                if (company.Id == reward.CompanyId)
                                {
                                    rewardsList.Add(new UserRewardsViewModel
                                    {
                                        companyName = company.Name,
                                        rewardName = reward.RewardName
                                    });
                                }
                            }
                        }
                    }
                }
            }

            return View(rewardsList);
        }
    }
}

PSI-X/Views/Rewards/AllRewards.cshtml
<br />
<br />
<br />
<h2>All rewards</h2>
<table class="table table-condensed">
    <tr>
        <th>Company name</th>
        <th>Reward</th>
        <th>Required points</th>
    </tr>
    @foreach (var reward in Model)
    {
        <tr>   
            <td>@reward.CompanyName</td>
            <td>@reward.RewardName</td>
            <td>@reward.RequiredPoints</td>    
        </tr>
    }
</table>

PSI-X/Views/Rewards/Index.cshtml
<br />
<br />
<br />
<h2>Available rewards</h2>
<table class="table table-condensed">
    <tr>
        <th>Company name</th>
        <th>Reward</th>
    </tr>
    @foreach (var reward in Model)
    {
        <tr>
            <td>@reward.companyName</td>
            <td>@reward.rewardName</td>
        </tr>
    }
</table>

PSI-X/Views/Rewards/Result.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<br />
<h2>@ViewBag.Message</h2>

PSI-X/Views/Rewards/SaveReward.cshtml
@model PSI_X.ViewModels.RewardAddViewModel

<div class="container">
    <h3 style="padding-top: 50px">Create new reward</h3>
    <hr />
    <div class="col-md-4 col-md-offset-4">
        @using (Html.BeginForm("SaveReward", "Rewards", FormMethod.Post))
        {
            <div class="form-group">

                @try
                {
                    <label>Company</label>
                    @Html.DropDownListFor(m => m.reward.CompanyId, new SelectList(Model.companies, "Id", "Name"), "", new { @class = "form-control" })
                }
                catch (NullReferenceException e)
                {

                }

            </div>
            <label>Name</label>
            @Html.TextBoxFor(model => model.reward.RewardName, new { @class = "form-control", placeholder = "Name" })
            <br />
            <label>Required Points</label>
            @Html.TextBoxFor(model => model.reward.RequiredPoints, new { @class = "form-control", @placeholder = "Points" })
            <br />
            <br />
            <input type="submit" value="Submit" class="btn btn-success" />
        }
    </div>
</div>